{{- range .Values.virtualServices }}
{{- if .enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .host | replace "." "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - {{ .host | quote }}
  gateways:
    - {{ .gateway | quote }}
  http:
    - match:
        - uri:
            prefix: {{ .uriPrefix }}
      route:
        - destination:
            host: {{ include "vector.fullname" $ }}
            port:
              number: {{ .port }}
---
{{- end }}
{{- end }}